name: signspeak
description: "Sign Language Translator."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  permission_handler: ^12.0.1
  gap: ^3.0.1
  flex_color_scheme: ^8.3.0
  camera: ^0.11.2
  image: ^4.5.4
  path_provider: ^2.1.5
  tflite_flutter: ^0.11.0
  path: ^1.9.1
  pose: ^1.1.7
  http: ^1.5.0
  supabase_flutter: ^2.10.1
  flutter_dotenv: ^6.0.0
  sqflite: ^2.4.2
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  hand_landmarker: ^2.1.0
  carousel_slider: ^5.1.1
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  speech_to_text: ^7.3.0
  cross_file: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/alphabet/
    - assets/logo.svg
    - assets/logo.png
    - .env
